"use client";

import { useState } from "react";
import { jsPDF } from "jspdf";
import { Download, FileText, Loader2 } from "lucide-react";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { FitnessPlan } from "@/types/plan";

interface ExportPDFProps {
    plan: FitnessPlan | null;
    userName?: string;
}

export function ExportPDF({ plan, userName = "User" }: ExportPDFProps) {
    const [isExporting, setIsExporting] = useState(false);

    const handleExport = async () => {
        if (!plan) return;

        setIsExporting(true);

        try {
            const doc = new jsPDF();
            const pageWidth = doc.internal.pageSize.getWidth();
            let y = 20;

            // Header
            doc.setFillColor(11, 11, 11);
            doc.rect(0, 0, pageWidth, 40, "F");

            doc.setTextColor(204, 255, 0);
            doc.setFontSize(24);
            doc.setFont("helvetica", "bold");
            doc.text("AI.COACH", 20, 25);

            doc.setTextColor(150, 150, 150);
            doc.setFontSize(10);
            doc.text(`Personalized Plan for ${userName}`, 20, 33);

            doc.setTextColor(0, 0, 0);
            y = 55;

            // User Summary
            doc.setFontSize(12);
            doc.setFont("helvetica", "normal");
            doc.text(plan.user_summary, 20, y, { maxWidth: pageWidth - 40 });
            y += 20;

            // Daily Motivation
            doc.setFillColor(240, 255, 200);
            doc.roundedRect(15, y - 5, pageWidth - 30, 20, 3, 3, "F");
            doc.setFontSize(10);
            doc.setFont("helvetica", "italic");
            doc.text(`"${plan.daily_motivation}"`, 20, y + 7, { maxWidth: pageWidth - 45 });
            y += 30;

            // Workout Plan Section
            doc.setFont("helvetica", "bold");
            doc.setFontSize(16);
            doc.setTextColor(11, 11, 11);
            doc.text("🏋️ WORKOUT PLAN", 20, y);
            y += 10;

            doc.setFontSize(12);
            doc.text(plan.workout_plan.title, 20, y);
            doc.setFontSize(10);
            doc.setFont("helvetica", "normal");
            doc.text(`Duration: ${plan.workout_plan.duration}`, 20, y + 6);
            y += 15;

            // Exercises
            plan.workout_plan.exercises.forEach((exercise, index) => {
                if (y > 250) {
                    doc.addPage();
                    y = 20;
                }

                doc.setFillColor(245, 245, 245);
                doc.roundedRect(15, y - 4, pageWidth - 30, 18, 2, 2, "F");

                doc.setFont("helvetica", "bold");
                doc.setFontSize(10);
                doc.text(`${index + 1}. ${exercise.name}`, 20, y + 3);

                doc.setFont("helvetica", "normal");
                doc.setFontSize(9);
                doc.text(
                    `${exercise.sets} sets × ${exercise.reps} reps | Rest: ${exercise.rest}`,
                    20,
                    y + 10
                );

                y += 22;
            });

            y += 10;

            // Diet Plan Section
            if (y > 200) {
                doc.addPage();
                y = 20;
            }

            doc.setFont("helvetica", "bold");
            doc.setFontSize(16);
            doc.text("🥗 DIET PLAN", 20, y);
            y += 8;

            doc.setFontSize(11);
            doc.text(`Total Calories: ${plan.diet_plan.total_calories} kcal`, 20, y);
            y += 12;

            // Meals
            plan.diet_plan.meals.forEach((meal) => {
                if (y > 260) {
                    doc.addPage();
                    y = 20;
                }

                doc.setFillColor(250, 250, 230);
                doc.roundedRect(15, y - 4, pageWidth - 30, 22, 2, 2, "F");

                doc.setFont("helvetica", "bold");
                doc.setFontSize(10);
                doc.text(`${meal.label}: ${meal.name}`, 20, y + 4);

                doc.setFont("helvetica", "normal");
                doc.setFontSize(9);
                doc.text(
                    `Protein: ${meal.macros.p} | Carbs: ${meal.macros.c} | Fats: ${meal.macros.f}`,
                    20,
                    y + 12
                );

                y += 26;
            });

            // Footer
            const totalPages = doc.getNumberOfPages();
            for (let i = 1; i <= totalPages; i++) {
                doc.setPage(i);
                doc.setFontSize(8);
                doc.setTextColor(150, 150, 150);
                doc.text(
                    `Generated by AI.COACH | Page ${i} of ${totalPages}`,
                    pageWidth / 2,
                    doc.internal.pageSize.getHeight() - 10,
                    { align: "center" }
                );
            }

            // Save the PDF
            doc.save(`AI_Coach_Plan_${userName.replace(/\s+/g, "_")}.pdf`);
        } catch (error) {
            console.error("PDF export error:", error);
        } finally {
            setIsExporting(false);
        }
    };

    return (
        <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
            <Button
                variant="outline"
                size="sm"
                onClick={handleExport}
                disabled={!plan || isExporting}
                className="gap-2"
            >
                {isExporting ? (
                    <Loader2 size={14} className="animate-spin" />
                ) : (
                    <FileText size={14} />
                )}
                Export PDF
            </Button>
        </motion.div>
    );
}

// Export function for use in FloatingActions
export async function exportPlanAsPDF(
    plan: FitnessPlan,
    userName: string = "User"
): Promise<void> {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;

    // Simplified export for standalone function
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("AI.COACH - Fitness Plan", 20, y);
    y += 15;

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(`Plan for: ${userName}`, 20, y);
    y += 20;

    // Workout
    doc.setFont("helvetica", "bold");
    doc.text("Workout Plan", 20, y);
    y += 10;
    doc.setFont("helvetica", "normal");

    plan.workout_plan.exercises.forEach((ex, i) => {
        doc.text(`${i + 1}. ${ex.name} - ${ex.sets}x${ex.reps}`, 25, y);
        y += 7;
        if (y > 270) {
            doc.addPage();
            y = 20;
        }
    });

    y += 10;

    // Diet
    doc.setFont("helvetica", "bold");
    doc.text("Diet Plan", 20, y);
    y += 10;
    doc.setFont("helvetica", "normal");

    plan.diet_plan.meals.forEach((meal) => {
        doc.text(`${meal.label}: ${meal.name}`, 25, y);
        y += 7;
        if (y > 270) {
            doc.addPage();
            y = 20;
        }
    });

    doc.save(`AI_Coach_Plan_${userName.replace(/\s+/g, "_")}.pdf`);
}
